import turtle
def f(x, y):
    turtle
    t = turtle.Turtle()
    t
    t.up()
    t.goto(x, y)
    t.width(7)
    t.left(90)
    t.forward(300)
    t.left(90)
    t.down()
    t.color('red')
    t.circle(300)
    t.up()
    t.goto(x, y)
    t.right(180)
    t.forward(500)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.down()
    t.color('blue')
    t.circle(20)
    t.left(90)
    t.up()
    t.forward(20)
    t.left(90)
    t.forward(80)
    t.left(90)
    t.forward(10)
    t.left(90)
    t.down()
    t.color('grey')
    t.circle(10)
def main():
    print('Введите координаты')
    x = input('Введите x: ')
    y = input('Введите y: ')
    while x != '' or y != '':
        x = int(x)
        y = int(y)
        f(x, y)
        print('Введите координаты')
        x = input('Введите x: ')
        y = input('Введите y: ')
main()
